// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzksaffvtjbqfptdnbcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6a3NhZmZ2dGpicWZwdGRuYmNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjI5MDksImV4cCI6MjA2NTUzODkwOX0.gAHPT7WK9QjpM1_Fy4oEj7zSBd8iw4r4ivproINrPFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);